services:
  # 後端 API 服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: linebot-web-backend
    ports:
      - "6000:8005"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - linebot-network

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linebot-web-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - linebot-network

networks:
  linebot-network:
    driver: bridge
