services:
  # 後端 API 服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: linebot-web-backend
    ports:
      - "8001:8005"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - linebot-network
    # 資源限制
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 768M
    # 日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        labels: "service=linebot-backend"

  # 前端服務
  frontend:
    build:
      context: .  # 使用專案根目錄作為構建上下文
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_UNIFIED_API_URL=https://api.jkl921102.org
        - VITE_WEBHOOK_DOMAIN=https://api.jkl921102.org
        - VITE_DOMAIN=https://api.jkl921102.org
        - REACT_APP_DOMAIN=https://api.jkl921102.org
        - VITE_ALLOWED_HOSTS=localhost,127.0.0.1,linebot.jkl921102.org,api.jkl921102.org
        - VITE_DEV_SERVER_HOST=0.0.0.0
        - VITE_DEV_SERVER_PORT=3000
        - VITE_PROXY_SECURE=true
        - VITE_PROXY_CHANGE_ORIGIN=true
    container_name: linebot-web-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - linebot-network
    # 資源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    # 日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        labels: "service=linebot-frontend"

networks:
  linebot-network:
    driver: bridge
