services:
  login_api:
    build:
      context: ./backend/loginAPI
      dockerfile: Dockerfile
    container_name: login_api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=sql.jkl921102.org
      - DB_PORT=5432
      - DB_NAME=LineBot_01
      - DB_USER=11131230
      - DB_PASSWORD=11131230
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=jerry1102.work@gmail.com
      - MAIL_PASSWORD=oozh giwd zcer czso
    ports:
      - "5501:5501"
    networks:
      - linebot_network
      - frontend
    restart: unless-stopped

  puzzle_api:
    build:
      context: ./backend/puzzleAPI
      dockerfile: Dockerfile
    container_name: puzzle_api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=sql.jkl921102.org
      - DB_PORT=5432
      - DB_NAME=LineBot_01
      - DB_USER=11131230 
      - DB_PASSWORD=11131230
    ports:
      - "5503:5503"
    networks:
      - linebot_network
      - frontend
    restart: unless-stopped

  line_login_api:
    build:
      context: ./backend/LINEloginAPI
      dockerfile: Dockerfile
    container_name: line_login_api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=sql.jkl921102.org
      - DB_PORT=5432
      - DB_NAME=LineBot_01
      - DB_USER=11131230
      - DB_PASSWORD=11131230
    ports:
      - "5502:5502"
    networks:
      - linebot_network
      - frontend
    restart: unless-stopped

  setting_api:
    build:
      context: ./backend/SettingAPI
      dockerfile: Dockerfile
    container_name: setting_api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=sql.jkl921102.org
      - DB_PORT=5432
      - DB_NAME=LineBot_01
      - DB_USER=11131230
      - DB_PASSWORD=11131230
      - PORT_SETTING=5004
    ports:
      - "5004:5004"
    networks:
      - linebot_network
      - frontend
    restart: unless-stopped

networks:
  linebot_network:
    name: linebot_network
    driver: bridge
  frontend:
    name: frontend
    external: true
