"""Add indexes, constraints and optimize schema

Revision ID: 7896f549eaa9
Revises: eb9cc5ef9175
Create Date: 2025-07-19 22:53:52.340309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7896f549eaa9'
down_revision: Union[str, None] = 'eb9cc5ef9175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bot_code_user_updated', 'bot_codes', ['user_id', 'updated_at'], unique=False)
    op.create_unique_constraint('unique_code_per_bot', 'bot_codes', ['bot_id'])
    op.create_index('idx_bot_user_created', 'bots', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint('unique_bot_name_per_user', 'bots', ['user_id', 'name'])
    # 添加 name 欄位並設定預設值
    op.add_column('flex_messages', sa.Column('name', sa.String(length=255), nullable=False, server_default="'Untitled Message'"))
    
    # 安全地轉換 TEXT 到 JSONB
    op.execute("ALTER TABLE flex_messages ALTER COLUMN content TYPE JSONB USING content::JSONB")
    
    # 移除預設值（僅用於 migration）
    op.alter_column('flex_messages', 'name', server_default=None)
    op.create_index('idx_flex_message_user_created', 'flex_messages', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint('unique_flex_message_name_per_user', 'flex_messages', ['user_id', 'name'])
    op.create_index('idx_user_created_verified', 'users', ['created_at', 'email_verified'], unique=False)
    op.create_index('idx_user_email_verified', 'users', ['email', 'email_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email_verified', table_name='users')
    op.drop_index('idx_user_created_verified', table_name='users')
    op.drop_constraint('unique_flex_message_name_per_user', 'flex_messages', type_='unique')
    op.drop_index('idx_flex_message_user_created', table_name='flex_messages')
    op.alter_column('flex_messages', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('flex_messages', 'name')
    op.drop_constraint('unique_bot_name_per_user', 'bots', type_='unique')
    op.drop_index('idx_bot_user_created', table_name='bots')
    op.drop_constraint('unique_code_per_bot', 'bot_codes', type_='unique')
    op.drop_index('idx_bot_code_user_updated', table_name='bot_codes')
    # ### end Alembic commands ###
