"""add_missing_admin_user_id_and_sender_type

Revision ID: f6797e183ef3
Revises: merge_heads_2025
Create Date: 2025-08-29 03:06:40.941516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6797e183ef3'
down_revision: Union[str, None] = 'merge_heads_2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_bot_user_interactions', sa.Column('sender_type', sa.String(length=20), nullable=True))
    op.add_column('line_bot_user_interactions', sa.Column('admin_user_id', sa.UUID(), nullable=True))
    
    # 設置現有記錄的預設 sender_type 為 'user'
    op.execute("UPDATE line_bot_user_interactions SET sender_type = 'user' WHERE sender_type IS NULL")
    op.drop_index('idx_interaction_media_path', table_name='line_bot_user_interactions', postgresql_where='(media_path IS NOT NULL)')
    op.create_index('idx_interaction_admin_user', 'line_bot_user_interactions', ['admin_user_id'], unique=False)
    op.create_index('idx_interaction_sender_type', 'line_bot_user_interactions', ['sender_type'], unique=False)
    op.create_index('idx_interaction_time_extract', 'line_bot_user_interactions', ['timestamp'], unique=False)
    op.create_index('idx_interaction_timestamp_event', 'line_bot_user_interactions', ['timestamp', 'event_type'], unique=False)
    op.create_index('idx_interaction_user_sender', 'line_bot_user_interactions', ['line_user_id', 'sender_type', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'line_bot_user_interactions', 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_line_user_bot_followed', 'line_bot_users', ['bot_id', 'is_followed'], unique=False)
    op.create_index('idx_line_user_bot_interaction', 'line_bot_users', ['bot_id', 'last_interaction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_line_user_bot_interaction', table_name='line_bot_users')
    op.drop_index('idx_line_user_bot_followed', table_name='line_bot_users')
    op.drop_constraint(None, 'line_bot_user_interactions', type_='foreignkey')
    op.drop_index('idx_interaction_user_sender', table_name='line_bot_user_interactions')
    op.drop_index('idx_interaction_timestamp_event', table_name='line_bot_user_interactions')
    op.drop_index('idx_interaction_time_extract', table_name='line_bot_user_interactions')
    op.drop_index('idx_interaction_sender_type', table_name='line_bot_user_interactions')
    op.drop_index('idx_interaction_admin_user', table_name='line_bot_user_interactions')
    op.create_index('idx_interaction_media_path', 'line_bot_user_interactions', ['media_path'], unique=False, postgresql_where='(media_path IS NOT NULL)')
    op.drop_column('line_bot_user_interactions', 'admin_user_id')
    op.drop_column('line_bot_user_interactions', 'sender_type')
    # ### end Alembic commands ###
